### ISSUE TITLE
Join user to groups

### ISSUE THREAD

**Issue by ndeitch** [daniel-frak/keycloak-user-migration#11]
Hi, thanks for the lib!

Did you think about join users to groups during creation? We've a use case for this and I'm able to create a PR for it, but first I'd like to hear what you think about it.

I checked keycloak's [UserModel](https://github.com/keycloak/keycloak/blob/d59a74c364e9cee1fdfaf2fc7de21c9ecb1e5c6f/server-spi/src/main/java/org/keycloak/models/UserModel.java#L160) interface, and there is a `joinGroup` method I think calling this method do the job. My doubt is what happens if group doesn't exist.

Thanks

------

Requirements:

- [ ] Group Mapping
- [ ] Migrate unmapped groups
- [ ] Update user DTO with groups set (optional)
- [ ] Update documentation

**Comment by daniel-frak** [comment]
Handling user groups during migration sounds like a great idea!

That said, I think we might need some additional configuration for group mapping (similar to how it's currently handled for roles) - that is, a group map and a toggle to migrate unmapped groups.

That will also resolve the problem of "what to do if a group doesn't exist" - we should add it if the toggle is ON and ignore it if it's OFF (and actually ignore any groups not present in the group map in that case).

Adding the new config options means we should probably also update the screenshot in the `Optional - additional configuration` section of the README.md.

Last but not least, this will most likely require updating the User DTO to include a `groups` field of some sort - this field should not be mandatory and should be documented as such in README.md.

If you're up for it, that would be a great contribution to the project :)

**Comment by ndeitch** [comment]
Sounds great!

I updated issue with requirements for this feature, this the local implementation I did:

```java
if (legacyUser.getGroups() != null) {
    legacyUser.getGroups().forEach(group ->
            ofNullable(realm.getGroupById(group)).ifPresentOrElse(
                    userModel::joinGroup,
                    () -> userModel.joinGroup(realm.createGroup(group))
            )
    );
}
```

I'll open this PR in the next few days
