### ISSUE TITLE
There are no requests made to the legacy API endpoint

### ISSUE THREAD

**Issue by macakraca** [daniel-frak/keycloak-user-migration#13]
## Describe the bug

I have completed the installation of the Keycloak server and the Feredation provider as described in the README file. The problem is that the user from the legacy database does not validate.

The error message from the login form:

> We are sorry...
> 
> Unexpected error when handling authentication request to identity provider.

From what I can tell **there are no requests made to the legacy API endpoint**.

### Some indications:

1. Keycloak logs WARN message

```sh
keycloak_1  | 15:17:53,532 WARN  [org.keycloak.events] (default task-25) type=LOGIN_ERROR, realmId=DemoRealm, clientId=account, userId=null, ipAddress=172.20.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=http://localhost:8024/auth/realms/DemoRealm/account/login-redirect, code_id=e545e494-603e-4f35-8758-765f5fd5527f, username=bob, authSessionParentId=e545e494-603e-4f35-8758-765f5fd5527f, authSessionTabId=izT3E0HXAu8
```

2. The API endpoint logging is silent, no request gets logged.

### 1. Keycloak

* install Keycloak application with provided docker-compose file
* open `http://localhost:8024` and login with `admin` user
* add new realm `DemoRealm`, use defaults (not sure if this is mandatory, though)
* add new client `DemoRealm`, use defaults (not sure if this is mandatory, though)
* create new `User Federation › User Migration Using A REST Client` as per instructions in the README
* add `http://localhost:3000/auth/` in the `Rest client URI` filed

Note: I'm not sure if legacy user should authenticate against `Master` realm, so I created a new realm.

### 2. Rest API endpoint

* clone [my example web server](https://github.com/macakraca/express-demo.git) repo
* install and run the **express node webserver** with `yarn && yarn start`

### 3. Login

* open browser and navigate to `DemoRealm` account address [http://localhost:8024/auth/realms/DemoRealm/account](http://localhost:8024/auth/realms/DemoRealm/account)
* enter username `bob` and password `password123` from the `data.js` file.

## Expected behavior

* there should be a log entry in the node console describing each `GET` or `POST` request
* the user `bob` should be able to log in

**Comment by daniel-frak** [comment]
I think the problem is that you're running the Keycloak instance within the Docker container, so it can't "see" any services outside of its sandboxed network. As a result, Keycloak can't call the legacy API because - as far as it's concerned - it doesn't exist.

One option would be to add your example web server to the docker-compose and define a common network for them.

Another option, if memory serves, would be to simply add `network_mode: "host"` and remove the `ports` definition from the docker-compose.

Let me know if this helps!

**Comment by macakraca** [comment]
You ar right, it is a docker related problem. Services don't see each other on the docker network.

However, the `network_mode: "host"` with keycloak service doesn't work:
`java.net.BindException: [UDP] /172.20.0.1 is not a valid address on any local network interface`

So I've created Dockerfile for the legacy service (express) and combined both services in one compose file.

Both services needs to be on the same network.

```yaml
    ...
    networks:
      - bridge
```

The network has a _bridge_ driver.

```yaml
networks:
  bridge:
    driver: bridge
```

In User Federation settings `Rest client URI` points to the `network name:internal port` of the service, e.g.:

`http://express:3000/auth/`

It works now. Thanks.
