### ISSUE TITLE
Support fort 23.X

### ISSUE THREAD

**Issue by gregoryb** [daniel-frak/keycloak-user-migration#140]
Hello,

We are on 23.0.5. Is your provider compatible or do you plan to support it ?

Thank you.

**Comment by daniel-frak** [comment]
Hello!

Adding support for 23.X should just be a matter of updating the dependencies and the docker-compose file.

I'll do it if I find some time, but I encourage you to create a PR for it if you feel like contributing :)

**Comment by gregoryb** [comment]
I'm at Java Level 0 👎 but i can try and of course I'll share if I can ;)

**Comment by daniel-frak** [comment]
I've updated the plugin to support Keycloak 23.X in v3.0.0:

https://github.com/daniel-frak/keycloak-user-migration/releases/tag/3.0.0
