### ISSUE TITLE
Fallback to Provider Password if Keycloak internal password is wrong

### ISSUE THREAD

**Issue by theomega** [daniel-frak/keycloak-user-migration#141]
I'm unsure how this should work in this plugin, so what the intended behaviour is.

What I would love to achieve, is that the users can change their passwords in the legacy system and still login. As keycloak stores the passwords after a successful login inside its own database, this would require, that, when the password of the user is invalid (from the point of view of the Keycloak Database), this plugin must be asked to check the password again.

I was assuming this is the behaviour, but I'm failing to get this working:

1. User A does not exist in Keycloak yet
2. User A enters his password "1" into the login form of keycloak
3. This plugin calls the REST GET endpoint getting the user info
4. This plugin calls the REST POST endpoint validating the password
5. Keycloak creates the user (with the password "1") inside its database
6. User can login
7. User changes his password in the legacy system to "2"
8. User tries to login again using "2" as their password
9. Without even calling the REST POST endpoint, keycloak complains about a wrong password.

Is this the desired behaviour? Can this be configured, so that in the step 9. keycloak first checks its own database for password matches and if it doesn't find a valid password, asks this plugin?

**Comment by theomega** [comment]
Thanks @daniel-frak , that totally makes sense, thanks for the explanation. I tried searching the issues, but didn't find that one. Maybe we should add this to the README, so that people know what to expect and save you from answering the same question again?

**Comment by daniel-frak** [comment]
That sounds like a great idea!

Do you want to make a PR for the README update?

**Comment by daniel-frak** [comment]
I've updated the docs to clarify the consequences of the link being severed.
Let me know if there's anything else you were thinking about adding there.
