### ISSUE TITLE
301 redirect when a request is sent without slash

### ISSUE THREAD

**Issue by dyohan9** [daniel-frak/keycloak-user-migration#15]
In systems that require the path in the url to have a slash, it immediately returns a status code 301, the provider is not prepared to deal with this redirection and interrupts the execution

## Reproduction
Add an endpoint that requires slash and return the 301 statuscode

**Comment by daniel-frak** [comment]
@dyohan9, I haven't yet had time to reproduce this issue on my own but do you have any ideas regarding what would have to be done to fix this? I would guess that the fault lies on the RESTEasy client but I don't have enough experience with it to know what would need to be done without further research.

**Comment by dyohan9** [comment]
> @dyohan9, I haven't yet had time to reproduce this issue on my own but do you have any ideas regarding what would have to be done to fix this? I would guess that the fault lies on the RESTEasy client but I don't have enough experience with it to know what would need to be done without further research.

I believe that simply adding a slash to the endpoints already solves the problem

**Comment by daniel-frak** [comment]
The newest version of the plugin should support redirects, so I'm closing this issue.

Let me know if there are any further problems.
