### ISSUE TITLE
Docker is required??

### ISSUE THREAD

**Issue by Muthurajj** [daniel-frak/keycloak-user-migration#157]
Doker is required to run this project, any other alternative way to run this project?

**Comment by daniel-frak** [comment]
Hi! Docker is only required for developing this plugin and serves as a reference for using it.

If you only want to use it, you need to download the version of this plugin appropriate for your Keycloak version and add it to Keycloak's `providers` folder (`/opt/keycloak/providers/` in the Docker example), then follow the instructions in README.md.
