### ISSUE TITLE
"User exists with same email" Error in kcadm.sh

### ISSUE THREAD

**Issue by siemendev** [daniel-frak/keycloak-user-migration#196]
Hi @daniel-frak!
When using the Plugin (Keycloak 25.0.4; Plugin 5.0.0) and adding a new user to the keycloak using `kcadm.sh` (like `kcadm.sh create users -r master -s username=testuser -s email=test@example.com -s enabled=true -s emailVerified=true`), the api responds with the following error: `User exists with same email`

When I delete the user federation provider everthing works, so I can pinpoint it to the user migration plugin. I use the Bitnami Image (Issue persists on the main image though).

Edit: I removed the logs since it turned out they are not related to this issue.

**Comment by daniel-frak** [comment]
I have tried replicating the issue using the docker-compose in this repository and the following command:

```
docker exec -it keycloak_migration_demo-keycloak-1 /opt/keycloak/bin/kcadm.sh create users -r master -s username=testuser -s email=test@example.com -s enabled=true -s emailVerified=true --server http://localhost:8080 --realm master --user admin --password admin
```

The result was:
```
Logging into http://localhost:8080 as user admin of realm master
Created new user with id 'e5509e84-b99b-4c46-bbbb-28ba4ef1437a'
```

Are you sure no user with the same e-mail exists when browsing `http://localhost:8024/admin/master/console/#/master/users` and searching for `*` (all users)?

If so, can you give steps to reproduce it using this repository's docker-compose? A Cypress test reproducing the issue would be even better.

Also, possible duplicate of #189.

**Comment by siemendev** [comment]
I think it was more of a misunderstanding combined with a timing issue. Since the migration plugin is a user federation provider, it will look up new users in the legacy database for existing users with the same email/username. Our system creates a legacy user first and then tries to create the user in Keycloak. this will not work with the migration plugin enabled (understandably). We changed the implementation to create the user first in keycloak and then in the legacy database.

Thanks for taking a look into it anyway!
