### ISSUE TITLE
Issue with keycloak 9

### ISSUE THREAD

**Issue by xavier-006** [daniel-frak/keycloak-user-migration#2]
Hello there is the following error with keycloak 9 : 

`Uncaught server error: java.lang.NoSuchMethodError: 'boolean org.keycloak.models.UserCredentialManager.updateCredential(org.keycloak.models.RealmModel, org.keycloak.models.UserModel, org.keycloak.credential.CredentialInput)'`

Can you please update your plugin ? 

Thank you for your work !

**Comment by maximebrun** [comment]
Hi,

I have the same problem with Keycloak 9. @xavier-006 , how did you fix that ?

Thank you
