### ISSUE TITLE
User migration with Keycloak 12.X

### ISSUE THREAD

**Issue by janezu** [daniel-frak/keycloak-user-migration#20]
Hi @daniel-frak, I know you've specified that the plugin is only compatible with 9.x and 11.x versions of keycloak (which have worked for me) but i tried using it with keycloak 12.0.2 and 12.03 as well. It seems like an error occurs inside UserModelFactory when the .addUser function is called on the session local storage. 

`[org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-3) SQL Error: 0, SQLState: null
[org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-3) IJ031013: Interrupted attempting lock: org.jboss.jca.adapters.jdbc.local.LocalManagedConnection@4e7d7cak4qb7
[org.keycloak.utils.ServicesUtils] (default task-3) Execution with object [com.danielfrak.code.keycloak.providers.rest.LegacyProvider@37c7bed6] exceeded specified time limit 3000.
[org.keycloak.services] (default task-3) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not prepare statement`

But the strange thing is, that if i retry the login with the same user multiple times it actually successfully migrates the user. Have you tried using the plugin and are you aware of this issue and what might be causing it?  Do you know why specifically the REST user migration plugin is not compatible with the newer versions of keycloak?

Thanks in advance!

**Comment by daniel-frak** [comment]
Hi,

I haven't yet had time to test the solution on Keycloak 12, though it should work if it's compiled with the proper version. Have you tried changing the `keycloak.version` in the POM before building the jar file?

@toddkazakov did it in his recent PR (which will hopefully be merged soon):
https://github.com/daniel-frak/keycloak-user-migration/pull/17

I haven't encountered this issue myself, though it seems like some sort of timeout is occurring within your database - it might be worth looking into this from that angle.

**Comment by weltonrodrigo** [comment]
I tried with Keycloak 12 and got the same behavior. In my case, the exception comes from a timeout of 3000ms given to the whole operation and my rest api takes some time to compile user roles from other services in the first call.

Also, debugging is impossible as any call to a method resulting in a database operation by Keycloak will throw.

**Comment by daniel-frak** [comment]
TBH, looking at it closely, it seems to be an issue between Keycloak and the database.
The only thing that comes to my mind at the moment is to try and increase the JDBC time limit in Keycloak's Wildfly config:

https://www.keycloak.org/docs/4.8/server_installation/#_database

http://docs.wildfly.org/13/Admin_Guide.html#DataSource

According to this source:

http://www.mastertheboss.com/jboss-server/jboss-datasource/jboss-datasource-configuration

The property needed might be `idle­-timeout­-minutes`.

Maybe then, at least, debugging this will get easier.

**Comment by DaBonse** [comment]
- Keycloak 12.0.4 in Docker environment
- PostgreSQL or internal H2 DB.
- Latest Plugin version.



Hello,

I think, I have the same timeout issue.

I have tested the plugin with a static Web service, which always return the same JSON content. In this test everything works fine. The user will be migrated.
Than, I wanted to develop my Web service to provide real data. This Web service is slower.

I run in this error, every time:


```
01:56:16,795 INFO [com.danielfrak.code.keycloak.providers.rest.remote.UserModelFactory] (default task-1) Creating user model for: ex@example.com

01:56:16,798 WARN [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) SQL Error: 0, SQLState: null

01:56:16,799 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) IJ031013: Interrupted attempting lock: org.jboss.jca.adapters.jdbc.local.LocalManagedConnection@1fc6b2d2

01:56:16,809 WARN [org.keycloak.utils.ServicesUtils] (default task-1) Execution with object [com.danielfrak.code.keycloak.providers.rest.LegacyProvider@1d70ce63] exceeded specified time limit 3000.

01:56:16,811 WARN [org.keycloak.services] (default task-1) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not prepare statement
```


I am not a Java guy, so debugging is difficult for me. But I can say, the first GET request is successful, because the username ex@example.com comes from the Web service, and not from Keycloak login form.

I have wrote tests again static Web service and new real Web service. This two Web services deliver the same data and response codes.


I think its a timeout issue. How can I increase this timeout to verify and test it?


Thanks,

Alex

**Comment by weltonrodrigo** [comment]
Check Daniel's comment above.

https://github.com/daniel-frak/keycloak-user-migration/issues/20#issuecomment-863934662

You need to change that in standalone.xml in keycloak.

Check this: https://github.com/daniel-frak/keycloak-user-migration/issues/20#issuecomment-863934662

This file is located inside keycloak, probably on /opt/jboss/standalone/configuration/standalone.xml

**Comment by DaBonse** [comment]
Thanks for your reply.

I do not have this directory structure or this file in my Keycloak Docker container:

`/opt/jboss/standalone/configuration/standalone.xml `


but I found a standalone.xml here:

`/opt/jboss/keycloak/standalone/configuration/standalone.xml`

In this xml file there is no option idle­-timeout­-minutes (or similar) I can change. And I have absolutely no idea how and where to insert this configuration option. 

Is this the right config file?

Can you provide an config example please?


Thanks,
Alex

**Comment by weltonrodrigo** [comment]
> Can you provide an config example please?

I gave you the wrong link in the last comment. I meant to point you this: https://www.keycloak.org/docs/4.8/server_installation/#modify-the-keycloak-datasource

You can see an example of this setting on this question: https://stackoverflow.com/questions/28645435/database-connections-not-closed-after-idle-timeout-in-wildfly-datasource

**Comment by DaBonse** [comment]
Good morning weltonrodrigo,

thanks for your reply. I have made the changes you suggested. But no effect. 

I think, in my case, there is no idle timeout problem. Because, after creating a new Keycloak container and testing the migration first time, the error still exists. There was no time for something to be idle.

The error message above

`01:56:16,809 WARN ... exceeded specified time limit 3000.`

speaks from a time limit of 3000. I think this is in ms. This value does not change, when I changed the timeout value in the xml config file.

I have also tried different JDBC_PARAMS in my docker-compose.yml like:

```
environment:
- ...
- JDBC_PARAMS="connectTimeout=90000&statement_timeout=90000"
```

But also no effect.

Is there anything else I can try?

Thanks,
Alex

**Comment by weltonrodrigo** [comment]
Well, I suppose you should investigate if your rest service is accessible and responding in less than 3000ms.

I was under the impression that you were trying to debug the keycloak-user-migration code.

I stumbled into similar error when my rest user service took longer than 3000ms to respond. I have no idea where to set this timeout.

**Comment by DaBonse** [comment]
Hello weltonrodrigo,

I was able to reduce the response time of my Web service extensively under one second, in my dev environment. After this performance boost, the error is gone and the migration works fine.

Now I am able to confirm, the error results in long response time of the Web service. 

Anyway, if anybody know how to increase this special timeout, it would be helpful in future.

Again, thank you very much weltonrodrigo, you helped me to solve the situation.

cu

Alex

**Comment by odelcroi** [comment]
Hello, 

I am facing a similar situation with a slow web service, does anyone found where to set this timeout? 

Thanks

**Comment by odelcroi** [comment]
For anyone wondering, there is a workaround explained here : 
https://stackoverflow.com/questions/68199153/is-there-a-way-to-configure-the-storageprovidertimeout-in-keycloak

and a bug report here : 
https://issues.redhat.com/browse/KEYCLOAK-18856

**Comment by daniel-frak** [comment]
I'm closing this one due to inactivity and because it seems that a solution was already given.
