### ISSUE TITLE
Add support for Client Roles

### ISSUE THREAD

**Issue by clahavya** [daniel-frak/keycloak-user-migration#21]
If the role is defined in keycloak as a Client Role rather than Realm Role it is not migrated
Adding something like the code below would make it look through client roles.

```javascript
RoleModel roleModel = realm.getRole(role);
        if(roleModel == null) {
            List<ClientModel> clients = realm.getClients();
            for(ClientModel client : clients) {
                roleModel = client.getRole(role);
                if(roleModel != null) {
                    break;
                }
            }
        }
```

**Comment by daniel-frak** [comment]
Thanks for the info!

Would you like to create a Pull Request with the change?

**Comment by clahavya** [comment]
> Would you like to create a Pull Request with the change?

Yes, I would like to do that.

**Comment by daniel-frak** [comment]
Great, thanks!
