### ISSUE TITLE
create release asset?

### ISSUE THREAD

**Issue by efossas** [daniel-frak/keycloak-user-migration#25]
Hello, would you be willing to create a release tag and upload the .jar file as a release asset?

I ask because I am using the keycloak operator which will install an extension for me if I provide it a url to the jar file.

**Comment by daniel-frak** [comment]
Sounds like something I could do, though I'll have to configure Github Actions to create the releases (I don't want to just do a one-off release that will grow obsolete with time).

I'm not sure when I'll get the time to do that but I'll update this issue when I do :)

**Comment by efossas** [comment]
sounds good, I appreciate that. I can actually do the work. I'll fork the repo, write a github action, and make a PR.

**Comment by daniel-frak** [comment]
That's great!
Do you think you could incorporate version changes in the POM, as well? Perhaps something like I have in Dummy4j (but without actually publishing on ossh):
https://github.com/daniel-frak/dummy4j/blob/master/.github/workflows/publish.yml

That's about as fancy as I managed to get with Github actions, myself :)

**Comment by daniel-frak** [comment]
I'm closing this due to finally getting around to creating the release workflow I wanted.

Thanks to everyone who contributed!
