### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jpatters** [daniel-frak/keycloak-user-migration#4]
Just curious what the license of this is. Would you mind adding one please?

**Comment by daniel-frak** [comment]
The license is basically "do whatever you want with it", though I could make it explicit by adding one to the repo.

Do you think the MIT license would be a good choice?

**Comment by jpatters** [comment]
You should definitely add it to the repo. No one can legally use it until you do. MIT would be appropriate given your description.
Thanks
