### ISSUE TITLE
Reset password doesn't work

### ISSUE THREAD

**Issue by chucksellick** [daniel-frak/keycloak-user-migration#40]
The plugin is installed and working correctly, but when a user tries to do "reset pasword" I see an error "An unexpected error has occurred". Investigating debug logs on the server, I see a SQL error that a duplicate entry (of a user record with the same email address) is attempted to be created. Has anybody else tried reset password with this plugin?

![image](https://user-images.githubusercontent.com/1188786/132204230-3d572102-3848-4f39-9034-516fe453d12f.png)

**Comment by chucksellick** [comment]
![image](https://user-images.githubusercontent.com/1188786/132204193-3f09c8d3-513b-46be-ad3d-0071a5b8515f.png)

**Comment by chucksellick** [comment]
See comments in the following issue as it turns out to be the same issue: https://github.com/daniel-frak/keycloak-user-migration/issues/39

**Comment by daniel-frak** [comment]
Duplicate of #39.

Closing this one to keep the conversation focused on one thread.
