### ISSUE TITLE
User data migrated although password validation endpoint (POST) returns response with status NOT 200

### ISSUE THREAD

**Issue by swc-kdzekov** [daniel-frak/keycloak-user-migration#55]
Hello,
I'm testing the plugin for user data migration to Keycloak. Almost all works fine, except the case when the user is found (the GET end point), but the password is invalid (POST end-point). 
The first endpoint returns "ResponseEntity" with the user data and "HttpStatus.OK".
The second endpoint returns  "ResponseEntity" with "HttpStatus.BAD_REQUEST".

**What happens is that the user data is transferred to Keycloak and the user is not able to login to the application.**

I would expect that if the password endpoint (POST) returns status different than 200, the user data should not be moved to Keycloak at all. 
My question is, is it how it is supposed to work, or there is something that is missing?

These are my endpoints:
```
    @GetMapping("/user-client/{username}")
    public ResponseEntity<UserData> getUser(@PathVariable("username") String username) {
        return new ResponseEntity<>(prepareDummyUser(username), HttpStatus.OK);
    }

    @PostMapping("/user-client/{username}")
    public ResponseEntity validatePassword(@PathVariable("username") String username, @RequestBody Password password) {
        return new ResponseEntity(HttpStatus.BAD_REQUEST);
    }
```

The user data is not migrated only when the first (GET) endpoint returns HttpStatus.BAD_REQUEST.

**Comment by daniel-frak** [comment]
Indeed, both `LegacyProvider::getUserByUsername` and `LegacyProvider::getUserByEmail` call `UserModelFactory::create`, which then creates the user in Keycloak and sets up a federation link to the legacy system - that way only the credentials will get verified against the legacy system in the future, with no need to make the `GET` call (for user details) again .

Once the user logs in successfully, `LegacyProvider::updateCredential` gets called, severing the link to the legacy system entirely.

Is there anything in the plugin's behavior that's preventing your migration from going smoothly?

**Comment by swc-kdzekov** [comment]
Hi @daniel-frak . Yes, this confirms what I assumed. With updated description it is even more clear.

[Is there anything in the plugin's behavior that's preventing your migration from going smoothly?]

No, It works quite nicely actually. We tested it with hard-coded data up to now (which is enough to test the plugin). 
Thanks.

**Comment by daniel-frak** [comment]
Glad to have helped! :)
