### ISSUE TITLE
Turn into Kotlin ?

### ISSUE THREAD

**Issue by neogeogre** [daniel-frak/keycloak-user-migration#63]
Really nice and clean work guys,
If you want to move to the next level I can turn it into Kotlin for you, it will remove tons of boilerplate code.
Give me a green-light if you want me to do it.

**Comment by daniel-frak** [comment]
Thanks for the interesting offer!
However, as I'm the main maintainer of this codebase and I'm not well-versed in Kotlin at the moment, I don't think it would be a good idea right now.
