### ISSUE TITLE
Keycloak 19 version 

### ISSUE THREAD

**Issue by ibox4real** [daniel-frak/keycloak-user-migration#64]
Are there any plans to support Keycloak version 19?

**Comment by daniel-frak** [comment]
Yes, there are :)

I'll do it whenever I find a bit of time (should be soon now that you brought it to my attention), though I encourage you to make a PR if you need it ASAP :)

**Comment by ibox4real** [comment]
I will need to get familiar with Java at some to effectively tackle this myself, but thank you for the quick response.

**Comment by daniel-frak** [comment]
It seems we're both in luck as @Guy-Incognito has just created #65 to solve this issue :)
I suspect that MR will soon be merged into the main branch.

**Comment by daniel-frak** [comment]
The aforementioned PR has been merged into the main branch and so the plugin should work with Keycloak 19 without problems now :)
