### ISSUE TITLE
Other legacy system examples?

### ISSUE THREAD

**Issue by xgp** [daniel-frak/keycloak-user-migration#70]
Hi! Thanks for the great project.

I'm looking to see if you are aware of other legacy system examples? I see the example in the `legacy-system-example` dir, but I wanted to check if you were aware of others in the wild. I'm working with people that are using Django and Passport (username-password strategy) and wanted to check before I build them.

Thank you!

**Comment by daniel-frak** [comment]
I'm afraid I'm not sure what you mean. The `legacy-system-example` is just an example of how to implement the REST endpoints necessary for the migration plugin to work. You should be able to implement these in any language or framework :)

**Comment by xgp** [comment]
Hi @daniel-frak. Sorry I was unclear. I was just asking if you were aware of **other** examples of how to implement the REST endpoints necessary for the migration plugin to work. I.e. in other languages or frameworks.

**Comment by daniel-frak** [comment]
Unfortunately, I don't know of any examples other than the one provided in the repository. The chance of them existing on a public repository are also slim, as I imagine anyone who created such an example would create a Pull Request for this project.

**Comment by xgp** [comment]
Thanks!
