### ISSUE TITLE
doesnt synchronize users

### ISSUE THREAD

**Issue by imonursahin** [daniel-frak/keycloak-user-migration#78]
I did the steps in the explanations with the example rest in the project, but when I want to log in with the user information, it does not see the users. I wrote a new rest service, likewise, it does not synchronize users and does not transfer them to keycloak. Where could I be doing wrong?

**Comment by daniel-frak** [comment]
Hi!
It's hard to say what the cause may be with the information you have given.
1) Are you using the plugin with the correct version of Keycloak (currently 21.X)?
1) Have you tried debugging the code?
2) Have you configured the plugin in Keycloak? What does that configuration look like?
3) Are any calls to your REST service being made? Have you checked the requests/responses there?

**Comment by imonursahin** [comment]
thanks. i solved the problem i had this problem because i wasnt use https
